# Remove cache directories generated by ruff and pytest
clean:
	rm -rf .ruff_cache
	rm -rf .pytest_cache

# Check for formatter errors using ruff
format:
	ruff format --check .

# Check for linter errors using ruff
lint:
	ruff check .

# Run unit tests using pytest
test:
	pytest

# Build and publish package to PyPI
publish:
	python -m build
	twine upload dist/*
